# Generated by Django 4.2.1 on 2023-05-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_skill_vacancy_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
