# Generated by Django 4.2.1 on 2023-05-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_skill_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
